import type { Clinic, Professional } from "@/lib/catalog/types";

export const CLINICS: readonly Clinic[] = [
  {
    id: "atelier-pinheiros",
    name: "Ateliê Pinheiros",
    slug: "atelier-pinheiros",
    regionId: "sao-paulo",
    neighborhood: "Pinheiros",
    address: "Rua dos Pinheiros, 1480 — Pinheiros, São Paulo",
    inOdontoHubNetwork: true,
    note: "Consultório no Hub. A agenda, o prontuário e o retorno já estão no mesmo arquivo.",
  },
  {
    id: "estudio-vila-mariana",
    name: "Estúdio Vila Mariana",
    slug: "estudio-vila-mariana",
    regionId: "sao-paulo",
    neighborhood: "Vila Mariana",
    address: "Rua Domingos de Morais, 2564 — Vila Mariana, São Paulo",
    inOdontoHubNetwork: true,
    note: "Endodontia com evolução clínica no OdontoHub. O paciente não precisa repetir a história.",
  },
  {
    id: "clinica-moema",
    name: "Clínica Moema",
    slug: "clinica-moema",
    regionId: "sao-paulo",
    neighborhood: "Moema",
    address: "Av. Ibirapuera, 3103 — Moema, São Paulo",
    inOdontoHubNetwork: true,
    note: "Cirurgia de siso com confirmação automática. Menos recados. Mais presença.",
  },
  {
    id: "jardins-orto",
    name: "Jardins Ortodontia",
    slug: "jardins-ortodontia",
    regionId: "sao-paulo",
    neighborhood: "Jardins",
    address: "Alameda Santos, 2400 — Jardins, São Paulo",
    inOdontoHubNetwork: true,
    note: "Acompanhamento mensal no Hub. O retorno não se perde.",
  },
  {
    id: "itaim-reab",
    name: "Itaim Reabilitação",
    slug: "itaim-reabilitacao",
    regionId: "sao-paulo",
    neighborhood: "Itaim Bibi",
    address: "Rua Joaquim Floriano, 72 — Itaim Bibi, São Paulo",
    inOdontoHubNetwork: true,
    note: "Implante e prótese no mesmo arquivo clínico.",
  },
  {
    id: "atelier-jardins",
    name: "Ateliê Jardins",
    slug: "atelier-jardins",
    regionId: "sao-paulo",
    neighborhood: "Jardins",
    address: "Rua Oscar Freire, 379 — Jardins, São Paulo",
    inOdontoHubNetwork: true,
    note: "Estética com fotografia clínica organizada por paciente.",
  },
  {
    id: "madalena-perio",
    name: "Madalena Periodontia",
    slug: "madalena-periodontia",
    regionId: "sao-paulo",
    neighborhood: "Vila Madalena",
    address: "Rua Harmonia, 118 — Vila Madalena, São Paulo",
    inOdontoHubNetwork: true,
    note: "Gengiva, manutenção e lembretes de retorno no Hub.",
  },
  {
    id: "copacabana-hub",
    name: "Copacabana Studio",
    slug: "copacabana-studio",
    regionId: "rio-de-janeiro",
    neighborhood: "Copacabana",
    address: "Av. Nossa Senhora de Copacabana, 680 — Copacabana, Rio de Janeiro",
    inOdontoHubNetwork: true,
    note: "Clínica geral com agenda silenciosa. Se não há urgência, o sistema não interrompe.",
  },
  {
    id: "botafogo-canal",
    name: "Botafogo Canal",
    slug: "botafogo-canal",
    regionId: "rio-de-janeiro",
    neighborhood: "Botafogo",
    address: "Rua Voluntários da Pátria, 190 — Botafogo, Rio de Janeiro",
    inOdontoHubNetwork: true,
    note: "Canal com registro de dor e retorno já no prontuário.",
  },
  {
    id: "ipanema-cirurgia",
    name: "Ipanema Cirurgia",
    slug: "ipanema-cirurgia",
    regionId: "rio-de-janeiro",
    neighborhood: "Ipanema",
    address: "Rua Visconde de Pirajá, 550 — Ipanema, Rio de Janeiro",
    inOdontoHubNetwork: true,
    note: "Siso e extrações. Orientações pós-operatórias saem do Hub, não de um papel solto.",
  },
  {
    id: "tijuca-urgencia",
    name: "Tijuca Atendimento",
    slug: "tijuca-atendimento",
    regionId: "rio-de-janeiro",
    neighborhood: "Tijuca",
    address: "Rua Conde de Bonfim, 255 — Tijuca, Rio de Janeiro",
    inOdontoHubNetwork: true,
    note: "Janelas de urgência. O Hub mostra o que pode entrar hoje.",
  },
  {
    id: "savassi-kids",
    name: "Savassi Infantil",
    slug: "savassi-infantil",
    regionId: "belo-horizonte",
    neighborhood: "Savassi",
    address: "Rua Pernambuco, 1000 — Savassi, Belo Horizonte",
    inOdontoHubNetwork: true,
    note: "Odontopediatria. A ficha da criança nasce no mesmo arquivo da família.",
  },
  {
    id: "lourdes-implante",
    name: "Lourdes Implante",
    slug: "lourdes-implante",
    regionId: "belo-horizonte",
    neighborhood: "Lourdes",
    address: "Av. do Contorno, 6400 — Lourdes, Belo Horizonte",
    inOdontoHubNetwork: true,
    note: "Reabilitação. Planejamento e fotos no Hub.",
  },
  {
    id: "batel-orto",
    name: "Batel Ortodontia",
    slug: "batel-ortodontia",
    regionId: "curitiba",
    neighborhood: "Batel",
    address: "Av. do Batel, 1868 — Batel, Curitiba",
    inOdontoHubNetwork: true,
    note: "Aparelho e alinhador. Manutenções com confirmação no Presença.",
  },
  {
    id: "moinhos-studio",
    name: "Moinhos Studio",
    slug: "moinhos-studio",
    regionId: "porto-alegre",
    neighborhood: "Moinhos de Vento",
    address: "Rua Padre Chagas, 66 — Moinhos de Vento, Porto Alegre",
    inOdontoHubNetwork: true,
    note: "Dentística. Restauração com registro fotográfico.",
  },
  {
    id: "boa-viagem-geral",
    name: "Boa Viagem Clínica",
    slug: "boa-viagem-clinica",
    regionId: "recife",
    neighborhood: "Boa Viagem",
    address: "Av. Boa Viagem, 1200 — Boa Viagem, Recife",
    inOdontoHubNetwork: true,
    note: "Prevenção e clínica geral. A revisão não depende da memória da recepção.",
  },
  {
    id: "arvores-perio",
    name: "Caminho das Árvores",
    slug: "caminho-das-arvores",
    regionId: "salvador",
    neighborhood: "Caminho das Árvores",
    address: "Alameda das Framboesas, 82 — Caminho das Árvores, Salvador",
    inOdontoHubNetwork: true,
    note: "Periodontia e estética gengival. Retornos no Hub.",
  },
  {
    id: "asa-sul-protese",
    name: "Asa Sul Prótese",
    slug: "asa-sul-protese",
    regionId: "brasilia",
    neighborhood: "Asa Sul",
    address: "CLS 216, Bloco B — Asa Sul, Brasília",
    inOdontoHubNetwork: true,
    note: "Prótese e dentadura. O arquivo clínico viaja com o paciente.",
  },
  {
    id: "centro-floripa",
    name: "Centro Florianópolis",
    slug: "centro-florianopolis",
    regionId: "florianopolis",
    neighborhood: "Centro",
    address: "Rua Felipe Schmidt, 310 — Centro, Florianópolis",
    inOdontoHubNetwork: true,
    note: "DTM e placa. A queixa de dor fica no prontuário, não no WhatsApp.",
  },
];

export const PROFESSIONALS: readonly Professional[] = [
  {
    id: "helena-vasconcelos",
    slug: "helena-vasconcelos",
    name: "Helena Vasconcelos",
    honorific: "Dra.",
    cro: "CRO-SP 78.441",
    specialtyIds: ["dentistica", "clinica-geral"],
    intentIds: ["dentistica", "prevencao", "urgencia"],
    clinicId: "atelier-pinheiros",
    years: 11,
    acceptsNewPatients: true,
    bio: "Reconstrói dentes que lascaram no almoço e restaurações que soltaram no pão francês. Trabalha com calma, sem pressa de vender o próximo procedimento.",
    treats: ["Dente lascado ou quebrado", "Restauração que caiu", "Cárie em dente posterior"],
    approach: "Primeiro escuta o que aconteceu. Depois mostra, no espelho, o que dá para devolver no mesmo dia.",
  },
  {
    id: "ana-luisa-freire",
    slug: "ana-luisa-freire",
    name: "Ana Luísa Freire",
    honorific: "Dra.",
    cro: "CRO-SP 91.208",
    specialtyIds: ["odontopediatria"],
    intentIds: ["pediatrica", "prevencao"],
    clinicId: "atelier-pinheiros",
    years: 9,
    acceptsNewPatients: true,
    bio: "Recebe a criança antes do medo crescer. Primeira consulta sem luva na cara, com o encosto da cadeira ainda baixo.",
    treats: ["Primeira consulta infantil", "Dente de leite", "Dor em criança"],
    approach: "O adulto fala pouco. A criança mostra o dente quando quiser.",
  },
  {
    id: "rafael-monteiro",
    slug: "rafael-monteiro",
    name: "Rafael Monteiro",
    honorific: "Dr.",
    cro: "CRO-SP 64.902",
    specialtyIds: ["endodontia"],
    intentIds: ["endodontia", "urgencia"],
    clinicId: "estudio-vila-mariana",
    years: 14,
    acceptsNewPatients: true,
    bio: "Canal quando a dor lateja à noite. Explica o que é nervo sem desenho de terror.",
    treats: ["Dor de dente profunda", "Tratamento de canal", "Abscesso"],
    approach: "Alívio primeiro. O restante do canal, no ritmo que o dente aguentar.",
  },
  {
    id: "camila-duarte",
    slug: "camila-duarte",
    name: "Camila Duarte",
    honorific: "Dra.",
    cro: "CRO-SP 70.115",
    specialtyIds: ["cirurgia-bucomaxilofacial"],
    intentIds: ["cirurgia", "urgencia"],
    clinicId: "clinica-moema",
    years: 12,
    acceptsNewPatients: true,
    bio: "Siso incluso, extração, o dente que não cabe. Cirurgia com o pós-operatório escrito, não falado correndo na porta.",
    treats: ["Siso", "Dente incluso", "Extração"],
    approach: "Se pode esperar, espera. Se não pode, opera com a orientação já no telefone do paciente.",
  },
  {
    id: "thiago-nogueira",
    slug: "thiago-nogueira",
    name: "Thiago Nogueira",
    honorific: "Dr.",
    cro: "CRO-SP 55.330",
    specialtyIds: ["ortodontia"],
    intentIds: ["ortodontia"],
    clinicId: "jardins-orto",
    years: 16,
    acceptsNewPatients: true,
    bio: "Aparelho e alinhador. Não promete sorriso de revista em seis semanas.",
    treats: ["Aparelho fixo", "Alinhadores", "Mordida cruzada"],
    approach: "Mostra o que o osso permite. O prazo sai da biologia, não do marketing.",
  },
  {
    id: "beatriz-lemos",
    slug: "beatriz-lemos",
    name: "Beatriz Lemos",
    honorific: "Dra.",
    cro: "CRO-SP 82.774",
    specialtyIds: ["implantodontia", "protese"],
    intentIds: ["implante", "protese"],
    clinicId: "itaim-reab",
    years: 15,
    acceptsNewPatients: true,
    bio: "Reposição do dente que faltou. Implante quando o osso deixa. Prótese quando o implante ainda não é o caminho.",
    treats: ["Implante unitário", "Reabilitação", "Dente perdido"],
    approach: "Não começa pelo parafuso. Começa pela mastigação que a pessoa perdeu.",
  },
  {
    id: "lucas-andrade",
    slug: "lucas-andrade",
    name: "Lucas Andrade",
    honorific: "Dr.",
    cro: "CRO-SP 88.019",
    specialtyIds: ["estetica", "dentistica", "harmonizacao"],
    intentIds: ["estetica", "dentistica"],
    clinicId: "atelier-jardins",
    years: 10,
    acceptsNewPatients: true,
    bio: "Clareamento e forma. Recusa o sorriso padrão. Prefere o dente que ainda parece da pessoa.",
    treats: ["Dente escuro", "Clareamento", "Facetas pontuais"],
    approach: "Uma sessão de conversa antes de qualquer lente. Cor se discute com luz do dia.",
  },
  {
    id: "marina-costa",
    slug: "marina-costa",
    name: "Marina Costa",
    honorific: "Dra.",
    cro: "CRO-SP 61.447",
    specialtyIds: ["periodontia"],
    intentIds: ["periodontia", "prevencao"],
    clinicId: "madalena-perio",
    years: 13,
    acceptsNewPatients: true,
    bio: "Gengiva que sangra na escova. Periodontia sem sermão. Ensina o que a escova não alcança.",
    treats: ["Gengivite", "Periodontite", "Mau hálito"],
    approach: "Mede, mostra, combina a manutenção. O tártaro não volta se o retorno existir.",
  },
  {
    id: "pedro-henrique-alves",
    slug: "pedro-henrique-alves",
    name: "Pedro Henrique Alves",
    honorific: "Dr.",
    cro: "CRO-RJ 44.218",
    specialtyIds: ["clinica-geral"],
    intentIds: ["prevencao", "dentistica", "urgencia"],
    clinicId: "copacabana-hub",
    years: 8,
    acceptsNewPatients: true,
    bio: "Quem ainda não tem dentista. Consulta de rotina, a queixa solta, o que parece simples e às vezes não é.",
    treats: ["Limpeza", "Avaliação", "Dor recente"],
    approach: "Uma conversa. Um exame. Só então o nome do tratamento.",
  },
  {
    id: "fernanda-ribeiro",
    slug: "fernanda-ribeiro",
    name: "Fernanda Ribeiro",
    honorific: "Dra.",
    cro: "CRO-RJ 39.801",
    specialtyIds: ["endodontia"],
    intentIds: ["endodontia", "urgencia"],
    clinicId: "botafogo-canal",
    years: 11,
    acceptsNewPatients: true,
    bio: "Canal no Rio. Atende quem chegou depois de três noites em claro.",
    treats: ["Dor latejante", "Canal", "Retratamento"],
    approach: "Anestesia com tempo. Explicação curta. O dente, depois.",
  },
  {
    id: "joao-paulo-mendes",
    slug: "joao-paulo-mendes",
    name: "João Paulo Mendes",
    honorific: "Dr.",
    cro: "CRO-RJ 51.662",
    specialtyIds: ["cirurgia-bucomaxilofacial"],
    intentIds: ["cirurgia", "urgencia"],
    clinicId: "ipanema-cirurgia",
    years: 18,
    acceptsNewPatients: true,
    bio: "Siso de quem mora perto da praia e deixou inflamar duas vezes. Extração com o gelo já combinado.",
    treats: ["Siso incluso", "Extração", "Trauma"],
    approach: "Radiografia. Decisão. Orientações no Presença antes de sair da cadeira.",
  },
  {
    id: "renata-oliveira",
    slug: "renata-oliveira",
    name: "Renata Oliveira",
    honorific: "Dra.",
    cro: "CRO-RJ 47.990",
    specialtyIds: ["clinica-geral", "endodontia"],
    intentIds: ["urgencia", "endodontia", "dentistica"],
    clinicId: "tijuca-urgencia",
    years: 7,
    acceptsNewPatients: true,
    bio: "Urgência na Tijuca. Dente avulsionado, inchaço, a dor que não espera a segunda-feira.",
    treats: ["Trauma", "Inchaço", "Dor aguda"],
    approach: "Encaixa quem precisa. O restante da semana se reorganiza no Hub.",
  },
  {
    id: "sofia-carvalho",
    slug: "sofia-carvalho",
    name: "Sofia Carvalho",
    honorific: "Dra.",
    cro: "CRO-MG 22.450",
    specialtyIds: ["odontopediatria"],
    intentIds: ["pediatrica", "prevencao"],
    clinicId: "savassi-kids",
    years: 10,
    acceptsNewPatients: true,
    bio: "Crianças em Belo Horizonte. Dente de leite escuro, a primeira cárie, o medo herdado do pai.",
    treats: ["Odontopediatria", "Dente de leite", "Prevenção infantil"],
    approach: "A cadeira vira conversa. O motorzinho espera.",
  },
  {
    id: "eduardo-pires",
    slug: "eduardo-pires",
    name: "Eduardo Pires",
    honorific: "Dr.",
    cro: "CRO-MG 18.773",
    specialtyIds: ["implantodontia", "protese"],
    intentIds: ["implante", "protese"],
    clinicId: "lourdes-implante",
    years: 20,
    acceptsNewPatients: true,
    bio: "Implante e protocolo. Trabalha a reabilitação como devolver o almoço, não como catálogo de parafuso.",
    treats: ["Implante", "Protocolo", "Prótese sobre implante"],
    approach: "Planejamento em silêncio. Cirurgia quando o modelo já está certo.",
  },
  {
    id: "carolina-stein",
    slug: "carolina-stein",
    name: "Carolina Stein",
    honorific: "Dra.",
    cro: "CRO-PR 14.208",
    specialtyIds: ["ortodontia"],
    intentIds: ["ortodontia"],
    clinicId: "batel-orto",
    years: 12,
    acceptsNewPatients: true,
    bio: "Ortodontia no Batel. Aparelho para quem atrasou a decisão e para quem chegou cedo demais.",
    treats: ["Aparelho", "Alinhador", "Apinhamento"],
    approach: "Foto, modelo, prazo honesto. Manutenção pontual.",
  },
  {
    id: "henrique-bauer",
    slug: "henrique-bauer",
    name: "Henrique Bauer",
    honorific: "Dr.",
    cro: "CRO-RS 19.554",
    specialtyIds: ["dentistica", "clinica-geral"],
    intentIds: ["dentistica", "prevencao"],
    clinicId: "moinhos-studio",
    years: 9,
    acceptsNewPatients: true,
    bio: "Restauração em Porto Alegre. O dente que partiu no churrasco de domingo.",
    treats: ["Dente quebrado", "Restauração", "Cárie"],
    approach: "Mesma sessão quando dá. Sempre com a foto do antes no Hub.",
  },
  {
    id: "isabela-nunes",
    slug: "isabela-nunes",
    name: "Isabela Nunes",
    honorific: "Dra.",
    cro: "CRO-PE 11.320",
    specialtyIds: ["clinica-geral"],
    intentIds: ["prevencao", "dentistica", "periodontia"],
    clinicId: "boa-viagem-geral",
    years: 8,
    acceptsNewPatients: true,
    bio: "Quem precisa de um dentista e ainda não tem. Limpeza, revisão, a queixa sem nome.",
    treats: ["Check-up", "Limpeza", "Primeira consulta"],
    approach: "Escuta inteira. Encaminha se a especialidade pedir.",
  },
  {
    id: "gustavo-rocha",
    slug: "gustavo-rocha",
    name: "Gustavo Rocha",
    honorific: "Dr.",
    cro: "CRO-BA 16.881",
    specialtyIds: ["periodontia", "estetica"],
    intentIds: ["periodontia", "estetica"],
    clinicId: "arvores-perio",
    years: 14,
    acceptsNewPatients: true,
    bio: "Gengiva e sorriso. Recuo gengival, sangramento, a linha que mudou o sorriso.",
    treats: ["Periodontite", "Enxerto gengival", "Sorriso gengival"],
    approach: "A base primeiro. Estética depois, se ainda fizer sentido.",
  },
  {
    id: "andre-figueiredo",
    slug: "andre-figueiredo",
    name: "André Figueiredo",
    honorific: "Dr.",
    cro: "CRO-DF 8.442",
    specialtyIds: ["protese", "implantodontia"],
    intentIds: ["protese", "implante"],
    clinicId: "asa-sul-protese",
    years: 17,
    acceptsNewPatients: true,
    bio: "Prótese na Asa Sul. Dentadura que não cai no almoço. Coroa que não denuncia.",
    treats: ["Prótese removível", "Coroa", "Dentadura"],
    approach: "Prova. Ajuste. Outra prova. A pressa não mastiga por ninguém.",
  },
  {
    id: "lucia-amaral",
    slug: "lucia-amaral",
    name: "Lúcia Amaral",
    honorific: "Dra.",
    cro: "CRO-SC 9.775",
    specialtyIds: ["dtm", "clinica-geral"],
    intentIds: ["dtm", "urgencia"],
    clinicId: "centro-floripa",
    years: 13,
    acceptsNewPatients: true,
    bio: "Estalo, ranger, a mandíbula que trava de manhã. DTM sem aparelho milagroso.",
    treats: ["Bruxismo", "Dor na ATM", "Placa miorrelaxante"],
    approach: "Escuta o hábito. Mede a abertura. A placa é ferramenta, não destino.",
  },
];
