import type { CareIntent } from "@/lib/intent/types";

/**
 * Dental need taxonomy for OdontoHub Care.
 * Phrases are written in everyday Brazilian Portuguese, then normalized at match time.
 * Expandable to an LLM later; this layer stays the source of truth.
 */
export const CARE_INTENTS: readonly CareIntent[] = [
  {
    id: "dentistica",
    label: "Restauração dental",
    patientLabel: "Isso parece restauração",
    explanation: "Dente lascado, quebrado ou restauração que caiu. Encontre profissionais que restauram a forma e a função do dente.",
    specialtyIds: ["dentistica", "clinica-geral"],
    phrases: [
      "dente quebrou",
      "dente quebrado",
      "dente lascou",
      "dente lascado",
      "dente racho",
      "dente rachou",
      "dente trincou",
      "dente trincado",
      "restauração caiu",
      "restauracao caiu",
      "obturação caiu",
      "obturacao caiu",
      "massa caiu",
      "massa do dente",
      "massa do dente caiu",
      "a massa caiu",
      "tampão caiu",
      "tampao caiu",
      "buraco no dente",
      "dente com buraco",
      "cárie",
      "carie",
      "dente cariado",
      "quero restaurar",
      "preciso restaurar",
      "restauração",
      "restauracao",
      "obturação",
      "obturacao",
      "dente descascou",
      "pedaço do dente",
      "pedaco do dente",
      "dente partiu",
      "dente partido",
      "quebra no dente",
      "dente lasca",
    ],
  },
  {
    id: "endodontia",
    label: "Tratamento de canal",
    patientLabel: "Isso parece canal",
    explanation: "Dor profunda, latejante ou que acorda à noite pode precisar de avaliação para tratamento de canal.",
    specialtyIds: ["endodontia", "clinica-geral"],
    phrases: [
      "dor de dente",
      "dente doendo",
      "dente dói",
      "dente doi",
      "dor latejando",
      "dor latejante",
      "dente latejando",
      "dor que acorda",
      "acordando de dor",
      "canal",
      "tratamento de canal",
      "dentista para canal",
      "fazer canal",
      "tirar o nervo",
      "dente inflamado",
      "dente vivo doendo",
      "pulpite",
      "abscesso no dente",
      "inchaço na gengiva",
      "inchaco na gengiva",
      "bola de pus",
      "gengiva inchada perto do dente",
      "dor ao mastigar",
      "dói quando mordo",
      "doi quando mordo",
      "sensibilidade forte",
      "dente lateja",
      "dor insuportável",
      "dor insuportavel",
      "dente podre por dentro",
    ],
  },
  {
    id: "cirurgia",
    label: "Extração ou siso",
    patientLabel: "Isso parece cirurgia",
    explanation: "Siso, dente incluso ou extração. Encontre profissionais que atendem esses casos.",
    specialtyIds: ["cirurgia-bucomaxilofacial", "clinica-geral"],
    phrases: [
      "siso",
      "sisos",
      "dentista para siso",
      "dente do siso",
      "dente siso",
      "tirar o siso",
      "tirar siso",
      "extrair siso",
      "extração de siso",
      "extracao de siso",
      "siso doendo",
      "siso está doendo",
      "siso esta doendo",
      "siso incluso",
      "siso nascendo",
      "siso inflamado",
      "cisos",
      "dente incluso",
      "dente ciso",
      "extração",
      "extracao",
      "dentista para extração",
      "dentista para extracao",
      "dentista para extração de dente",
      "extrair dente",
      "arrancar dente",
      "tirar o dente",
      "tirar um dente",
      "dente para extrair",
      "cirurgia no dente",
      "dente siso inchado",
      "pericoronarite",
    ],
  },
  {
    id: "ortodontia",
    label: "Aparelho ou alinhador",
    patientLabel: "Isso parece ortodontia",
    explanation: "Dentes desalinhados ou alteração na mordida. Ortodontistas trabalham com aparelho fixo e alinhadores.",
    specialtyIds: ["ortodontia"],
    phrases: [
      "aparelho",
      "dentista para aparelho",
      "colocar aparelho",
      "quero aparelho",
      "aparelho nos dentes",
      "aparelho dentário",
      "aparelho dentario",
      "alinhador",
      "invisalign",
      "alinhadores",
      "dente torto",
      "dentes tortos",
      "dente torto",
      "dentes encavalados",
      "dente encavalado",
      "apertado os dentes",
      "dentes apinhados",
      "mordida errada",
      "mordida cruzada",
      "diastema",
      "dente separado",
      "vão entre os dentes",
      "vao entre os dentes",
      "ortodontia",
      "ortodontista",
      "corrigir o sorriso",
      "alinhar os dentes",
      "dente para frente",
      "dente saindo",
    ],
  },
  {
    id: "implante",
    label: "Implante dental",
    patientLabel: "Isso parece implante",
    explanation: "Falta um dente, ou vários. Implantes e próteses podem recuperar a mastigação e o sorriso.",
    specialtyIds: ["implantodontia", "protese"],
    phrases: [
      "implante",
      "implantes",
      "dentista para implante",
      "preciso de implante",
      "quero implante",
      "colocar implante",
      "fazer implante",
      "dente perdido",
      "perdi um dente",
      "falta um dente",
      "sem dente",
      "buraco onde era o dente",
      "reabilitação",
      "reabilitacao",
      "reabilitação oral",
      "reabilitacao oral",
      "pino no osso",
      "parafuso no dente",
      "substituir dente",
      "o dente caiu",
      "dente que caiu",
      "perdi o dente",
      "extraí e quero repor",
      "extrai e quero repor",
      "protocolo",
      "carga imediata",
      "all on four",
      "all-on-4",
    ],
  },
  {
    id: "pediatrica",
    label: "Dentista para crianças",
    patientLabel: "Isso parece dentista infantil",
    explanation: "Primeira consulta, dente de leite ou dor em criança. Encontre profissionais de odontopediatria.",
    specialtyIds: ["odontopediatria"],
    phrases: [
      "dentista infantil",
      "dentista de criança",
      "dentista de crianca",
      "odontopediatria",
      "odontopediatra",
      "meu filho",
      "minha filha",
      "meu bebe",
      "meu bebê",
      "criança",
      "crianca",
      "crianças",
      "criancas",
      "dente de leite",
      "dentes de leite",
      "primeira consulta criança",
      "primeira consulta crianca",
      "filho com dor de dente",
      "filha com dor",
      "criança com cárie",
      "crianca com carie",
      "dente de leite preto",
      "chupeta",
      "dedo na boca",
      "nenezinho",
      "neném",
      "nenem",
      "pediatra dos dentes",
      "dentista para criança",
      "dentista para crianca",
      "dentista infantil",
    ],
  },
  {
    id: "estetica",
    label: "Clareamento ou estética dental",
    patientLabel: "Isso parece estética",
    explanation: "Cor, manchas ou formato dos dentes. Conheça opções como clareamento e ajustes de forma, quando indicados.",
    specialtyIds: ["estetica", "dentistica", "harmonizacao"],
    phrases: [
      "dente escuro",
      "dente está escuro",
      "dente esta escuro",
      "dentes amarelos",
      "dente amarelo",
      "dente manchado",
      "dentes manchados",
      "clareamento",
      "dentista para clareamento",
      "clarear os dentes",
      "branquear dente",
      "dente branco",
      "quero dentes brancos",
      "faceta",
      "facetas",
      "lente de contato dental",
      "lentes de contato",
      "sorriso",
      "estética",
      "estetica",
      "estética dental",
      "estetica dental",
      "harmonização",
      "harmonizacao",
      "botox sorriso",
      "gengiva aparente",
      "sorriso gengival",
      "dente preto",
      "dente escureceu",
      "mancha no dente",
    ],
  },
  {
    id: "periodontia",
    label: "Cuidado com a gengiva",
    patientLabel: "Isso parece periodontia",
    explanation: "Gengiva que sangra, recua ou dói. Periodontistas cuidam dos tecidos que sustentam os dentes.",
    specialtyIds: ["periodontia"],
    phrases: [
      "gengiva sangrando",
      "gengiva sangra",
      "dentista para gengiva",
      "sangue na escova",
      "sangramento gengival",
      "gengiva inchada",
      "gengivite",
      "periodontite",
      "gengiva retraída",
      "gengiva retraida",
      "gengiva descendo",
      "raiz aparente",
      "mau hálito",
      "mau halito",
      "hálito ruim",
      "halito ruim",
      "dente mole",
      "dentes moles",
      "tártaro",
      "tartaro",
      "sarro",
      "gengiva doendo",
      "dor na gengiva",
      "periodontia",
      "limpeza profunda",
      "raspagem",
    ],
  },
  {
    id: "prevencao",
    label: "Limpeza ou consulta de rotina",
    patientLabel: "Isso parece uma consulta de rotina",
    explanation: "Limpeza profissional, revisão ou primeira consulta. Encontre dentistas de clínica geral.",
    specialtyIds: ["clinica-geral"],
    phrases: [
      "limpeza",
      "limpeza nos dentes",
      "quero limpeza",
      "limpeza dental",
      "limpeza dos dentes",
      "dentista para limpeza",
      "check up",
      "checkup",
      "consulta de rotina",
      "revisão",
      "revisao",
      "avaliação",
      "avaliacao",
      "primeira consulta",
      "dentista perto",
      "preciso de um dentista",
      "procurando dentista",
      "consulta odontológica",
      "consulta odontologica",
      "prevenção",
      "prevencao",
      "manutenção",
      "manutencao",
      "ver os dentes",
      "exame clínico",
      "exame clinico",
    ],
  },
  {
    id: "protese",
    label: "Prótese ou dentadura",
    patientLabel: "Isso parece prótese",
    explanation: "Prótese fixa, removível ou dentadura. Encontre profissionais para repor dentes perdidos.",
    specialtyIds: ["protese", "implantodontia"],
    phrases: [
      "prótese",
      "protese",
      "prótese dentária",
      "protese dentaria",
      "dentadura",
      "ponte",
      "ponte fixa",
      "coroa",
      "coroa no dente",
      "dente de porcelana",
      "prótese removível",
      "protese removivel",
      "prótese protocol",
      "overdenture",
      "dente artificial",
      "placa dentária",
      "placa dentaria",
    ],
  },
  {
    id: "dtm",
    label: "Dor na mandíbula ou bruxismo",
    patientLabel: "Isso parece ATM ou bruxismo",
    explanation: "Estalo, dor na mandíbula ou ranger dos dentes. Encontre profissionais que avaliam esses sintomas.",
    specialtyIds: ["dtm", "clinica-geral"],
    phrases: [
      "bruxismo",
      "range os dentes",
      "ranger os dentes",
      "aperto os dentes",
      "aperto de dente",
      "placa de bruxismo",
      "placa miorrelaxante",
      "atm",
      "dtm",
      "articulação",
      "articulacao",
      "mandíbula estalando",
      "mandibula estalando",
      "estalo na mandíbula",
      "estalo na mandibula",
      "dor na mandíbula",
      "dor na mandibula",
      "dor no ouvido dente",
      "não abre a boca",
      "nao abre a boca",
      "trismo",
      "dor na face",
    ],
  },
  {
    id: "urgencia",
    label: "Urgência",
    patientLabel: "Isso parece urgência",
    explanation: "Trauma, dente deslocado ou inchaço forte precisam de avaliação rápida. Consulte a disponibilidade da clínica.",
    specialtyIds: ["clinica-geral", "cirurgia-bucomaxilofacial", "endodontia"],
    phrases: [
      "urgência",
      "urgencia",
      "dentista para urgência",
      "dentista para urgencia",
      "emergência",
      "emergencia",
      "agora",
      "hoje ainda",
      "não aguento",
      "nao aguento",
      "dente saiu",
      "dente arrancou",
      "bati a boca",
      "cai de boca",
      "trauma no dente",
      "dente avulsionado",
      "dente para fora",
      "inchaço no rosto",
      "inchaco no rosto",
      "rosto inchado",
      "abscesso",
      "celulite facial",
      "sangrando muito",
    ],
  },
] as const;

export const INTENT_BY_ID = Object.fromEntries(
  CARE_INTENTS.map((intent) => [intent.id, intent]),
) as Record<CareIntent["id"], CareIntent>;
